version: '3'
services:
    #nginx
    web:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

    app:
      build:
        dockerfile: ./php-docker/Dockerfile
      volumes:
        - ./app:/var/www/html
      environment:
        MYSQL_HOST: db
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}

    db:
      image: mysql:8.0
      volumes:
        - mysqldata:/var/lib/mysql
      ports:
        - "4306:3306"
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USER: user
        MYSQL_PASSWORD: secret
        MYSQL_DATABASE: dockerphp

volumes:
  mysqldata: